apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanevents-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tanevents
  template:
    metadata:
      labels:
        app: tanevents
    spec:
      containers:
      - name: tanevents
        image: numanraza/tanevents:latest
        ports:
        - containerPort: 3000